### ISSUE TITLE
Add support for AKS pod identity

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium-java#10]
## Description:
_[Add description of the task]_

**Comment by jyotsnaravikumar** [comment]
@evillgenius75 was able to restart container, the logs and the spring just paused until it was able to contact the KV after it received an MSI from Pod Identity

It was tested on webv against gelato on aks

06/02 07:40:19 200 181 static 4 True 15 /version
06/02 07:40:19 200 91 static 3 True 2916 /
06/02 07:40:19 200 160 static 3 True 41650 /swagger/helium.json
06/02 07:40:19 200 332 healthz 1 True 4 /healthz
06/02 07:40:19 200 51 static 2 True 48 /robots.txt
06/02 07:40:19 200 51 static 2 True 48 /robots1234.txt
06/02 07:40:20 200 289 PagedRead 4 True 44683 /api/actors
06/02 07:40:20 200 589 PagedRead 4 True 123659 /api/movies
06/02 07:40:20 200 61 PagedRead 2 True 205 /api/genres
06/02 07:40:21 200 208 SearchMovies 3 True 1043 /api/featured/movie
06/02 07:40:21 200 794 Healthz 0 True 1133 /healthz/ietf
06/02 07:40:22 200 78 DirectRead 2 True 348 /api/actors/nm0000031
06/02 07:40:22 200 105 DirectRead 3 True 7817 /api/actors/nm0000173
06/02 07:40:22 200 88 DirectRead 3 True 1007 /api/movies/tt0133093
06/02 07:40:22 200 476 SearchMovies 4 True 120706 /api/movies?genre=Action
06/02 07:40:22 200 241 SearchMovies 3 True 46975 /api/movies?year=1999
06/02 07:40:23 200 324 SearchMovies 3 True 52925 /api/movies?actorId=nm0000206
06/02 07:40:23 200 578 SearchMovies 4 True 23703 /api/movies?rating=8.5
06/02 07:40:24 200 298 SearchActors 3 True 9252 /api/actors?q=nicole
06/02 07:40:24 200 195 SearchMovies 2 True 9370 /api/movies?q=ring
