### ISSUE TITLE
KeyVaultClient Log Level is not set based on overall logging level and clear text secrets in log

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium-java#226]
## Description
Currently, they are set separately with no code to tie them together.  We need to mitigate on our end and follow-up with PG.

## Expected Behavior
- A map between app log level and KV log level
- Setting app log level should set the KV client log level appropriately
- Secrets should not be in clear text in logs

## Reproduce
1. Change application logging level to more strict than INFO
2. run app
3. observe KV log output
4. See KV logs and secrets

**Comment by jofultz** [comment]
I'll need to map log levels of TRACE, DEBUG, INFO, WARN, ERROR, and FATAL to the available levels for the KeyVault log levels:

BASIC | Logs only URLs, HTTP methods, and time to finish the request.
-- | --
BODY | Logs everything in BASIC, plus all the request and response body. Note that only payloads in plain text or plain text encoded in GZIP will be logged.
BODY_AND_HEADERS | Logs everything in HEADERS and BODY.
HEADERS | Logs everything in BASIC, plus all the request and response headers.
NONE | Logging is turned off.

Presently, I will map no log levels to KV level of BODY_AND_HEADERS as that logs secrets in clear text.

**Comment by jofultz** [comment]
My initial thoughts on mapping the KV to app log level:
KV Log Level | Description | App Log Level | Reason
-- | -- | -- | --
BASIC | Logs only URLs, HTTP methods, and time to finish the request. | WARN, ERROR, FATAL | Matching decreased information
BODY | Logs everything in BASIC, plus all the request and response body. Note that only payloads in plain text or plain text encoded in GZIP will be logged. | N/A | Unused as it will show plain text secrets
BODY_AND_HEADERS | Logs everything in HEADERS and BODY. | N/A | Unused as it will show plain text secrets
HEADERS | Logs everything in BASIC, plus all the request and response headers. | TRACE, DEBUG, INFO | Matching increased amount of information
NONE | Logging is turned off. | N/A | There is no matching general log level

**Comment by dsturgell** [comment]
File CSE Feedback @jofultz

**Comment by jofultz** [comment]
CSE Feedback: https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/354926
