### ISSUE TITLE
Set CosmosDB Log Level in Accordance with App Log Level

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium-java#228]
## Description:
Currently, the logging level for the CosmosDB client is not explicitly set.  We need to adjust the configuration for the client to set the log level based on the overall log level.

Sanjeev noted that we should be able to use a ResponseDiagnosticsProcessor to implement the capability: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb. 

This implementation should also give us perf metrics by default since we would be logging the CosmosDB values.

- References https://github.com/retaildevcrews/helium/issues/114

**Comment by jyotsnaravikumar** [comment]
@jofultz @bartr @dsturgell  :  we would need to swarm and define the acceptance criteria on this task in tomorrow's standup.

Options:

1. Do we need to explicitly query diagnostic logs from cosmosdb as mentioned in the task above?
    Point to note with this option we will be adding more logs and slowing performance.

2. Do we need to reduce the default logging that cosmosdb produces ?
    If we want to go with option we would need to work with CosmosDB team as it is internal to the SDK.

Based on the above task description I have implemented option (1) as in https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb and the results are below:  


13:16:45.670 [reactor-http-nio-7] INFO  com.cse.helium.app.controllers.ActorsController - getAllActors (query=Optional[tom], pageNumber=Optional[2], pageSize=Optional[5])
13:16:45.670 [reactor-http-nio-7] INFO  com.cse.helium.app.controllers.Controller - controller::getAll (query=Optional[tom], pageNumber=Optional[2], pageSize=Optional[5])
13:16:57.501 [cosmos-rntbd-nio-2-5] INFO  com.cse.helium.app.dao.BaseCosmosDbDao - logging in flatfeedresponse movies query0=Retrieved Document Count                 :              42              
Retrieved Document Size                  :           39535 bytes        
Output Document Count                    :              10              
Output Document Size                     :           10521 bytes        
Index Utilization                        :          100.00 %            
Total Query Execution Time               :       17.030000 milliseconds 
Query Preparation Times 
    Query Compilation Time               :        0.230000 milliseconds 
    Logical Plan Build Time              :        0.090000 milliseconds 
    Physical Plan Build Time             :        0.150000 milliseconds 
    Query Optimization Time              :        0.020000 milliseconds 
  Index Lookup Time                      :        0.710000 milliseconds 
  Document Load Time                     :       15.160000 milliseconds 
Runtime Execution Times 
    Query Engine Times                   :        0.290000 milliseconds 
    System Function Execution Time       :        0.010000 milliseconds 
    User-defined Function Execution Time :        0.000000 milliseconds 
  Document Write Time                    :        0.050000 milliseconds 
Client Side Metrics 
  Retry Count                            :               0              
  Request Charge                         :            5.77 RUs          
 
Partition Execution Timeline 
┌------------┬------------------------------------┬----------------┬----------------┬-------------┬-------------------┬-----------┐ 
│Partition Id│                         Activity Id│Start Time (UTC)│  End Time (UTC)│Duration (ms)│NUMBER of Documents│Retry Count│ 
├------------┼------------------------------------┼----------------┼----------------┼-------------┼-------------------┼-----------┤ 
│           0│263572e4-a5d7-11ea-a949-134517cc80c4│   20:16:46:5810│   20:16:57:4840│        903.0│                 10│          0│ 
└------------┴------------------------------------┴----------------┴----------------┴-------------┴-------------------┴-----------┘ 
 
Scheduling Metrics 
┌------------┬------------------┬-------------┬--------------┬--------------------┬---------------------┐ 
│Partition Id│Response Time (ms)│Run Time (ms)│Wait Time (ms)│Turnaround Time (ms)│NUMBER of Preemptions│ 
├------------┼------------------┼-------------┼--------------┼--------------------┼---------------------┤ 
│           0│                12│        10904│            13│               10917│                    1│ 
└------------┴------------------┴-------------┴--------------┴--------------------┴---------------------┘

**Comment by jofultz** [comment]
@jyotsnaravikumar I'm not following the requirement you stated about needing to query CosmosDB diagnostic logs.  The present issue is that CosmosDB logs information, but isn't in sync with the logging level that we set for the application.  So, we may set our application to log only error, but CosmosDB could still be logging info.  So, the link that Sanjeev might be a way of doing that, but I looked real quickly and it looks like you might also be able to add a log4j config for CosmosDB logger config and set it in there.  Take a look here: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-java-sdk-v4-sql#enable-client-sice-logging.

Check out the link and let's sync tomorrow on this.

**Comment by jyotsnaravikumar** [comment]
@jofultz : This description, approach and link mentioned here is about query CosmosDB diagnostic logs -  Sanjeev noted that we should be able to use a ResponseDiagnosticsProcessor to implement the capability: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb. 
 It's also linked to this https://github.com/retaildevcrews/helium/issues/114 

Based on your comments looks like option(2) is the requirement.

**Comment by jofultz** [comment]
@jyotsnaravikumar, the log4j config for the CosmosDB client is probably the easiest and I would start with that and only switch if it failed to behave how we want.

WRT looking at ResponseDiagnosticsProcessor as a possibility, the idea was that if we are capturing the information, we could decide when and how to log it.

**Comment by jyotsnaravikumar** [comment]
@jofultz : the 2.2.2 version of cosmosdb sdk log4j for logging and helium-java uses apache logging. 
Hence solution is using log4j.properties for configuring helium-java logs and logback.xml for configuring the cosmosdb sdk logs. 

Implemented it in the PR.
