### ISSUE TITLE
Add Log Level App to KeyVault Mapping to Documentation

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium-java#230]
## Description:
Once the PR #229 is complete the current mapping will be:

KV Log Level | Description | App Log Level | Reason
-- | -- | -- | --
BASIC | Logs only URLs, HTTP methods, and time to finish the request. | WARN, ERROR, FATAL | Matching decreased information
BODY | Logs everything in BASIC, plus all the request and response body. Note that only payloads in plain text or plain text encoded in GZIP will be logged. | N/A | Unused as it will show plain text secrets
BODY_AND_HEADERS | Logs everything in HEADERS and BODY. | TRACE, DEBUG | A custom log policy redacts plain text secrets.
HEADERS | Logs everything in BASIC, plus all the request and response headers. | INFO | Matching increased amount of information
NONE | Logging is turned off. | OFF | This level is not currently used

- References #229

**Comment by jofultz** [comment]
We now have a matrix of log adjustments.  This code adjustment for KV log level to app log level, a log4j2.properties to adjust the logger, and a logback.xml.  We need to identify how changes across the three affect each other.

**Comment by sivamu** [comment]
This table has been included in Joseph's doc changes in the associated PR.
