### ISSUE TITLE
Codespaces F5 experience

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium-java#255]
## Description:
- The F5 experience for Codespaces has errors.
- Need to update .devcontainer for a good VS Code Developer Experience

- References retaildevcrews/helium#396

**Comment by jyotsnaravikumar** [comment]
Updated the  .devcontainer with VSCode extensions from @jofultz. Compared them with vscode extensions from mac.

Steps done to test:

- Created a new codespace, with helium-java github repo and tested with the updated .devcontainer.
- Set KEVAULT_NAME and AUTH_TYPE environment on Codespaces terminal
- Run helium-java either from maven IDE or from command line. 
- App starts clean with no errors

**Comment by jyotsnaravikumar** [comment]
Closed this as part of PR https://github.com/retaildevcrews/helium-java/pull/259
