### ISSUE TITLE
Client Remains Connected on Certain Movie Queries

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium-java#284]
## Description
Using httpie or curl the client seems to stay connected and require and extra "enter" key or ctrl-c in order to end the request.  Using part of the predicates seem to return as expected.

**Failing Request**
http localhost:4120/api/movies?q=matrix&genre=action&year=2003

**Successful But Similar Requests**
- http localhost:4120/api/movies?year=2003
- http localhost:4120/api/movies?genre=action
- http localhost:4120/api/movies?q=matrix

## Expected Behavior
All queries listed above should complete once executed and require no additional input to close the client.

## Reproduce
1. Start running the app
2. In the terminal window issue the **Failing Request**
3. See it hung
4. Press "Enter" to close

## Additional Context
My guess is that the errors in the tests described in #283 are related to the same problem since they were timeouts on movie queries.

**Comment by joaquinrz** [comment]
The issue seems to happen when '&' is present. This can be avoided by using single quotes after http: `http 'localhost:4120/api/movies?q=matrix&genre=action&year=2003'` or escaping the & symbol : `http localhost:4120/api/movies?q=matrix\&genre=action\&year=2003`

**Comment by sivamu** [comment]
Going to close this issue since there's a resolution/workaround for the problem.
