### ISSUE TITLE
Add instructions to Readme for local dev setup with MSI (using Azure VM)

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-java#49]
## Description:
- Update README with instructions on how to set up the local dev environment on an Azure VM and how to set up Managed Identity to remove any need for storing client id/password/secret locally

**Comment by bartr** [comment]
This won't be necessary with the new SDKs

**Comment by bartr** [comment]
This is no longer necessary because the Java SDK supports using az cli credentials
