### ISSUE TITLE
Performance Benchmark queries on Actors, Movies, Genres, FeaturedMovie

### ISSUE THREAD

**Issue by jyotsnaravikumar** [retaildevcrews/helium-java#55]
## Description:
**Performance testing** 
Measure warm-up / average thruput on direct/search queries

**Movies**
/api/movies
/api/movies?actorid=nm0000206
/api/movies?genre=action
/api/movies?genre=sci-fi
/api/movies?genre=horro
/api/movies?toprated=true
/api/movies?year=1999

**Genres**
/api/genres

**Actors**
/api/actors
/api/actors/nm0000173
/api/actors?q=nicole

**Healthz**
/healthz/ietf

**Comment by jyotsnaravikumar** [comment]
references #29

**Comment by dsturgell** [comment]
Baseline: 25ms-30ms
