### ISSUE TITLE
Key-Vault MSI setup

### ISSUE THREAD

**Issue by jyotsnaravikumar** [retaildevcrews/helium-java#65]
## Description:
-
Reuse existing key-vault setup from gelato-kv from bartr subscription

**Comment by bartr** [comment]
we should use the bluebell or sherbet KVs as gelato has additional keys that we want to make sure we're not using.

**Comment by jofultz** [comment]
I've started working on this.  I have successfully fetched a value.  Now I need to look a the other implementations and figure out how to generalize it for the code base.  After that I'll prepare a cut for the MIKV version (ref: https://github.com/orgs/retaildevcrews/projects/1#card-32299181).

**Comment by dsturgell** [comment]
With that and the rewrite of Helium-Java, we should make sure that we deliver the code for MIKV-Java early (and then copy to a separate repo). Based on the planning discussions, I think we will address all of those requirements in the next couple of sprints. Note I'm not suggesting we "ship" MIKV-Java first, just address the requirements in code.
