### ISSUE TITLE
helium-java Webflux & MIKV design review

### ISSUE THREAD

**Issue by sanjeevdwivedi** [retaildevcrews/helium-java#99]
_This template is for capturing details needed for Design Review._  

# Design Review

## Introduction
The purpose of this Design Review is to review the assumption and design decisions made for the new version of Helium Java with the use of the Webflux async framework. In particular we are listing out:

- Structure of the Managed Identity and Keyvault access layer
- Structure of the Data Access Objects layer including the class hierarchy
- Structure of the Rest Controllers
- Structure of creating beans and configuration in order to be able to use the Webflux best testing framework.

## System Overview
To help understand the development of the new Helium Java platform, it is helpful to understand the following terminology from the SpringBoot platform that is used to annotate classes

- @Service : Components at the business logic layer. These are classes that form the core infrastructure of the app such as MIKV access layer of the CosmosDB layer
- @Configuration: A class that is used to load up and create configuration objects for the rest of the environment. Examples are the CosmosDBConfig class which loads up the credentials for CosmosDB and HeliumConfig class which loads up the BuildConfiguration for Version
- @Bean: A class instantiated and managed by the springboot IoC containers automatically.
- @RestController: A View class that will be utilizing @Bean, @Configuration and @Service classes to create a Rest Endpoint. 

The new helium-java codebase is based around the concept of reactive streams which was finalized and adopted as part of the Springboot async model in the form of Reactive Streams that introduced the Mono and Flux data type. It is beyond the scope of this document to explain these but a great resource for these is [present here in a 12 part tutorial](https://tech.io/playgrounds/929/reactive-programming-with-reactor-3/Intro)

In a succinct form, the concept of reactive streams is based on data types and APIs that can respond to requests in forms of non-blocking data streams where the caller can throttle the server and can ask for more data if it can consume it or ask the producer to pause or stop if the volume of the data cannot be consumed immediately. 

There are Javascript client libraries (see usage in WebTestClient in Unit Tests for an example) that are streams aware and can function in an optimal fashion with a reactive server component. However, even non-reactive clients can still utilize and benefit when servers implement reactive streams which provides the ability to create async non-blocking behavior solely on the server.

## Design Considerations
Here is a view of the controller and dependencies topology. We have mimicked the behavior of the existing projects to ensure that the structure of the code follows the same patterns for sake of comprehension, clarity and consistency.

![Helium-Java-Controllers](https://user-images.githubusercontent.com/1569855/76242750-2eef1380-6205-11ea-9f19-a6d4b7871497.png)

Following the security guidelines, we have moved away from storing all forms of secrets into application properties configuration file and are instead maintaining it in the Keyvault. A minimal config is maintained in the application.properties file that helps determine whether we should use CLI credentials or if using MSI, it points to the location of the Keyvault in azure.

The Keyvault client loads up all the keyvault secrets upfront during application startup to ensure that subsequent calls have these available.

At the Data access layer, the base class for all Data Access Objects (BaseCosmosDBDao) utilizes the Keyvault and loads up the CosmosDB Credentials so that DAO classes specific to scenarios have this functionality built in simply from deriving from this class.

We have mostly moved away and are currently refactoring out the last of Springboot Data Repository pattern (async still) which allows us to have codeless access to the Data Access Layer in form of auto-created springboot queries since the cosmos SDK provides that only when using the cosmos db key/url in application properties.  Instead we are creating queries by ourselves as that allows us to use the MIKV pattern in the code.

### Reusable/Adaptable and Secure

By utilizing the Base DAO classes, the Keyvault and the thin Rest Controllers, our architecture ensures that the code can act as a standalone example for how to extend and build more comprehensive services. Security has been the top of mind as illustrated by the use of MIKV even though it excludes using the CosmosDB Springboot auto-configured Repositories.

One point to note is that we have noticed that using the Webflux framework, we have hit some issues with the Unit Tests where the Unit Tests had difficulty auto-creating the IoC objects needed by Springboot. The SpringBoot system was not being able to locate and instantiate the objects needed for mocking the controllers etc. We have solved that problem by having explicit config classes that we can pass to the Tests as part of the Application Context. This lets the Unit tests create the Application Context and locate all the dependencies. This, in some ways does impact how the production code looks like by forcing us to split the configuration classes from the core logic and yet, in interest of Observability and testing, we have decided that this approach is well justified. 

### Design Review Checklist

- [ ] Design Review Meeting Scheduled
- [ ] Design Review approved by team consensus
- [ ] Initial tasks created as issues in main project and assigned to the project backlog with proper priority
- [ ] Test plan complete (unit, validation, smoke)
- [ ] Add "References #<issue number>" to relevant tasks

**Comment by jofultz** [comment]
Here is a view of the controller and dependencies topology:
![Helium-Java-Controllers](https://user-images.githubusercontent.com/1569855/76242750-2eef1380-6205-11ea-9f19-a6d4b7871497.png)

**Comment by sanjeevdwivedi** [comment]
Code review finished with team on 3/10.
